
pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- task: UseNode@1
  inputs:
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'exit'
    appType: 'webAppLinux'
    WebAppName: 'xyhome'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
