- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'exit'
    appType: 'webAppLinux'
    WebAppName: 'xyhome'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

- task: UseNode@1
  inputs: